apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: elasticsearch-logging-hpa
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: statefulset 
    name: elasticsearch-logging-hpa
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization